### ISSUE TITLE
Short Introduction Teaching and Exercise Time is Zero

### ISSUE THREAD

**Issue by mhamilt** [carpentries-incubator/python-humanities-lesson#5]
The Teaching and Exercise Time for the first lesson is set to zero. Taking a cue from [the Python Inflammation course](https://swcarpentry.github.io/python-novice-inflammation/01-intro/index.html), 20 - 30 minutes should suffice

**Comment by iaine** [comment]
Have made it 30 minutes. It would be useful to hear back if anyone has a different time.

**Comment by iaine** [comment]
Closing for now.
