### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by mhamilt** [carpentries-incubator/python-humanities-lesson#8]
[The data set links directly to another repository](https://carpentries-incubator.github.io/python-humanities-lesson/setup/).

For ease of use and to avoid confusion with learners, a possible approach would be to include the data set as part of a release within

- [The Data Set Repository itself](https://carpentries-incubator.github.io/python-humanities-lesson/setup/)
- The python humanities lesson repository.

Linking to particular files in a git repository for download is generally not a great idea. As is having `.zip` files in a repository. For sustainability and to avoid link rot, I'd personally recommend making a release for the dataset repository and including a `.zip` of the specific python data as part of the release.

**Comment by iaine** [comment]
I've changed it to the Python Humanities lesson from commit eff61038c69c92b7e17f5de6fabc0b1a71d2d053

The original link is from where the data was being edited. Moved to this repo for now.

**Comment by mhamilt** [comment]
This still does not render as a direct download link. I think the best thing to do would really be to wrap everything in a zip and have it as part of release.

[Python Inflammation links to a zip within the git itself which is then served out as a download link on the page](https://swcarpentry.github.io/python-novice-inflammation/setup.html#obtain-lesson-materials), though I still think this is a messy way to approach things.

In any case, it should be avoided that learners be required to copy-paste source text or navigate GitHub's interface in any way to download data for a carpentry.

## Suggested Approaches

- [The Data Set Repository itself](https://carpentries-incubator.github.io/python-humanities-lesson/setup/): Same as [The python humanities lesson repository](https://github.com/iaine/humanities-lesson-data/archive/master.zip): downloads as `humanities-lesson-data-master.zip`
    - There could also be a `data` branch to give a folder of `humanities-lesson-data-data.zip` with a download link of  https://github.com/iaine/humanities-lesson-data/archive/data.zip
- zipping [data](https://github.com/carpentries-incubator/python-humanities-lesson/tree/gh-pages/data) and adding it to `data`. Messy, but this the approach taken with other carpentries so at least there is precedence. 
- Link to the specific file with the GitHub Pages URL. i.e. `[Link to file]({{ site.url }}/path/to/file/in/repo.csv)` Since browsers will handle different file streams in their own way, we can't guarantee this will result in a download. To guarantee a download would require the usage of something like [`download.js`](http://danml.com/download.html) the amount of effort required to do that far outweighing any of the other methods.
